name: micro_commons_design_system
description: A new Flutter package project.
version: 1.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  golden_toolkit: 0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf